[tool.ruff]
target-version = "py311"
line-length = 100
indent-width = 2

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D1",    # undocumented
    "D203",  # one blank line before class
    "D213",  # multi-line summary second line
    "TD001", # invalid todo tag
    "S608", # SQL 文章内の文字列変数導入をチェック
    "COM812", "ISC001", "ANN204", "T201", "PTH123", "ERA001", "I001", "ANN401", "BLE001", "G004", "PTH110", "PTH107", "PTH118", "D415", "D400", "DTZ005", "PTH103", "INP001","TRY400",
]
unfixable = [
    "F401", # unused import
    "F841", # unused variable
]

logger-objects = ["common.log.logger"]

[tool.ruff.lint.pylint]
max-args = 6

[tool.ruff.lint.per-file-ignores]
"*.py" = [
  # at least this three should be fine in tests:
  "S101", # asserts allowed in tests...
  "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
  "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
  # The below are debateable
  "PLR2004", # Magic value used in comparison, ...
  "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]
